{
 "title": "Covid19",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country",
    "query": "select distinct country_name from covid19"
   }
  ]
 },
 "panels": [
  { "title": "Country", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last updated",
   "type": "table",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT MAX(time) as \"time\" FROM covid19 WHERE country_name = '$country'"
    }
   ]
  },
  {
   "title": "Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  death,\n  recovered,\n  confirmed-death-recovered \"active\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\") AND\n  country_name = '$country'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Ratio over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  confirmed-death-recovered AS \"active\",\n  death,\n  recovered\nFROM covid19\nWHERE\n  $__timeFilter(\"time\") AND\n  country_name = '$country'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Changes",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1d),\n  confirmed - lag(confirmed) OVER (ORDER BY $__timeGroup(\"time\",1d)) as \"confirmed\",\n  death - lag(death) OVER (ORDER BY $__timeGroup(\"time\",1d)) as \"death\",\n  recovered - lag(recovered) OVER (ORDER BY $__timeGroup(\"time\",1d)) as \"recovered\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\") AND \n  country_name = '$country' \nORDER BY 1"
    }
   ]
  },
  {
   "title": "New Cases / Day",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1d),\n  avg(death) - lag(avg(death)) OVER (ORDER BY $__timeGroup(\"time\",1d)) AS \"death\",\n  avg(confirmed) - lag(avg(confirmed)) OVER (ORDER BY $__timeGroup(\"time\",1d)) AS \"confirmed\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\") AND\n  country_name = '$country'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Cases (stacked)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  death,\n  recovered,\n  confirmed-death-recovered AS \"active\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\") AND\n  country_name = '$country'\nORDER BY 1"
    }
   ]
  },
  { "title": "Comparisons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Confirmed cases vs. total population",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  a.country_name AS \"Country\",\n  a.confirmed / b.population AS \"confirmed\"\nFROM covid19 a, population b\nWHERE\n  a.country_name = '$country' AND\n  a.country_code = b.country_code AND\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  a.country_name AS \"Country\",\n  a.confirmed / b.population AS \"confirmed\"\nFROM covid19 a, population b\nWHERE\n  a.country_code in ('BE', 'US', 'NL', 'MY', 'DE', 'FR', 'IT', 'ES') AND\n  a.country_code = b.country_code AND\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mortality vs. total population",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  a.country_name AS \"Country\",\n  a.death / b.population AS \"mortality\"\nFROM covid19 a, population b\nWHERE\n  a.country_name = '$country' AND\n  a.country_code = b.country_code AND\n  $__timeFilter(\"time\")\nORDER BY 1"
    },
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  a.country_name AS \"Country\",\n  a.death / b.population AS \"mortality\"\nFROM covid19 a, population b\nWHERE\n  a.country_code in ('BE', 'US', 'NL', 'MY', 'DE', 'FR', 'IT', 'ES') AND\n  a.country_code = b.country_code AND\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}