{
 "title": "Covid19 - internals",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Handler requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (target) (rate(simplejson_query_duration_seconds_count{app=~\"covid19\"}[2m]))",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Handler latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (app,target) (simplejson_query_duration_seconds_sum{app=\"covid19\"} / simplejson_query_duration_seconds_count{app=\"covid19\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Handler error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (target) (simplejson_query_failed_count{app=\"covid19\"} / simplejson_query_duration_seconds_count{app=\"covid19\"})",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (go_goroutines{app_kubernetes_io_name=\"covid19\"})"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (go_gc_duration_seconds_sum{app_kubernetes_io_name=\"covid19\"} / go_gc_duration_seconds_count)",
     "legendFormat": "duration"
    },
    {
     "expr": "sum by (app_kubernetes_io_name) (rate(go_memstats_frees_total{app_kubernetes_io_name=\"covid19\"}[2m]))",
     "legendFormat": "frees"
    },
    {
     "expr": "sum by (app_kubernetes_io_name) (rate(go_memstats_mallocs_total{app_kubernetes_io_name=\"covid19\"}[2m]))",
     "legendFormat": "allocs"
    }
   ]
  },
  {
   "title": "memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (go_memstats_sys_bytes{app_kubernetes_io_name=\"covid19\"})",
     "legendFormat": "sys"
    },
    {
     "expr": "sum by (app_kubernetes_io_name) (go_memstats_alloc_bytes{app_kubernetes_io_name=\"covid19\"})",
     "legendFormat": "alloc"
    },
    {
     "expr": "sum by (app_kubernetes_io_name) (go_memstats_heap_inuse_bytes{app_kubernetes_io_name=\"covid19\"})",
     "legendFormat": "heap"
    }
   ]
  },
  {
   "title": "database connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_name) (go_sql_in_use_connections{app_kubernetes_io_name=\"covid19\"})",
     "legendFormat": "in use"
    },
    {
     "expr": "sum by (app_kubernetes_io_name) (go_sql_open_connections{app_kubernetes_io_name=\"covid19\"})",
     "legendFormat": "open"
    }
   ]
  }
 ]
}