{
 "title": "Covid19 - World",
 "time": { "from": "now-1y", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Ratio",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "target": "death", "type": "timeserie" },
    { "target": "recovered", "type": "timeserie" },
    { "target": "active", "type": "timeserie" }
   ]
  },
  {
   "title": "Ratio over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "cumulative", "type": "table" }
   ]
  },
  {
   "title": "New cases / day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "daily", "type": "table" }
   ]
  },
  {
   "title": "Total cases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "cumulative", "type": "table" }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Confirmed cases by country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_name,\n  confirmed\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Death toll by country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_name,\n  death\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  { "title": "Maps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Confirmed Cases",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 31 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_code,\n  confirmed\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 31 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_code,\n  death\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Evolution",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 44 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(\"time\",1d),\n  country_code as \"metric\",\n  avg(confirmed-death-recovered) - lag(avg(confirmed-death-recovered)) OVER (PARTITION by country_code ORDER BY $__timeGroup(\"time\",1d)) AS \"value\"\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nGROUP BY 1, metric\nORDER BY 1, metric"
    }
   ]
  },
  {
   "title": "Infection vs. population (%)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 44 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  a.time as \"time\", \n  a.country_code,\n  CAST (100.0 * a.confirmed / b.population AS FLOAT) AS \"confirmed\"\nFROM covid19 a, population b \nWHERE \n  a.country_code = b.country_code and\n  $__timeFilter(\"time\")\nORDER BY 1,2;"
    }
   ]
  },
  {
   "title": "Mortality vs. confirmed cases (%)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 57 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  country_code,\n  100.0 * death / confirmed\nFROM covid19\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mortality vs. population (%%)",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 57 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  a.country_code,\n  1000.0 * death / population\nFROM covid19 a, population b\nWHERE\n  a.country_code = b.country_code AND\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  }
 ]
}