{
 "title": "Covid19 - API Server",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(grafana_datasource_request_duration_seconds_sum{datasource=\"covid19api\"}[2m]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "API performance (covid19api)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (path) (grafana_api_duration_seconds_sum / grafana_api_duration_seconds_count)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (rate(go_memstats_mallocs_total {app=\"covid19\"}[5m]))",
     "legendFormat": "mallocs"
    },
    {
     "expr": "sum by (app) (rate(go_memstats_frees_total {app=\"covid19\"}[5m]))",
     "legendFormat": "frees"
    }
   ]
  },
  {
   "title": "Go GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (app) (go_gc_duration_seconds_sum{app=\"covid19\"} / go_gc_duration_seconds_count{app=\"covid19\"})",
     "legendFormat": "GC duration"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(covid_reported_count{app=\"covid19\"})",
     "legendFormat": "last reported"
    }
   ]
  }
 ]
}