apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- pvc.yaml
- postgres-deployment.yaml
- postgres-service.yaml
- config.yaml
- service.yaml
- deployment.yaml
- cronjobs.yaml
secretGenerator:
- literals:
  - password=$COVID_PG_PASSWORD
  name: postgres
  type: Opaque
- literals:
  - api_key=$RAPIDAPI_KEY
  - notify_url=$COVID_SLACK_WEBHOOK
  - pg_password=$COVID_PG_PASSWORD
  name: covid19
  type: Opaque
images:
- name: ghcr.io/clambin/covid19-handler
  newTag: $TAG      
- name: ghcr.io/clambin/covid19-loader
  newTag: $TAG      
- name: ghcr.io/clambin/covid19-population-loader
  newTag: $TAG     
