// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/clambin/covid19/models"
)

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// GetCountryStats provides a mock function with given fields: ctx
func (_m *Fetcher) GetCountryStats(ctx context.Context) ([]models.CountryEntry, error) {
	ret := _m.Called(ctx)

	var r0 []models.CountryEntry
	if rf, ok := ret.Get(0).(func(context.Context) []models.CountryEntry); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.CountryEntry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
