apiVersion: v1
kind: ConfigMap
metadata:
  name: covid19-config
data:
  covid19.yml: |
    port: 5000
    debug: false
    postgres:
      host: postgres
      port: 5432
      database: "covid19"
      user: "covid"
    monitor:
      enabled: true
      interval: 20m
      rapidAPIKey: 
        envVar: "api_key"
      notifications:
        enabled: true
        url: 
          envVar: "notify_url"
        countries:
        - Belgium
    grafana:
      enabled: true
