apiVersion: v1
kind: Service
metadata:
  name: covid19
  labels:
    app: covid19
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: covid19
