// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NotificationSender is an autogenerated mock type for the NotificationSender type
type NotificationSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: title, message
func (_m *NotificationSender) Send(title string, message string) error {
	ret := _m.Called(title, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(title, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewNotificationSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewNotificationSender creates a new instance of NotificationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewNotificationSender(t mockConstructorTestingTNewNotificationSender) *NotificationSender {
	mock := &NotificationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
