apiVersion: v1
kind: Secret
metadata:
  name: covid19mon
type: Opaque
stringData:
  apikey: "__RAPIDAPIKEY__"
  pg_host: "postgres"
  pg_port: "5432"
  pg_database: "covid19"
  pg_user: "covid"
  pg_password: "__PGPASSWORD__"
  pushover_token: "__TOKEN__"
  pushover_user: "__USER__"
---
