// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// NotificationSender is an autogenerated mock type for the NotificationSender type
type NotificationSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: title, message
func (_m *NotificationSender) Send(title string, message string) error {
	ret := _m.Called(title, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(title, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
