name: Build

on:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ‘1.15.5’
    - name: checks
      run: |
        go get -u golang.org/x/lint/golint
        golint ./...
        go vet ./...
    - name: test
      run: |
        go test ./...
