name: Build

on:
  push:
    branches:
    - master
    - refactor

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.16
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: test
        run: |
          export pg_host=postgres
          export pg_port=5432
          export pg_database=postgres
          export pg_user=postgres
          export pg_password=postgres
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v2.1.0
        with:
          file: coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ covid19, backfill ]
        platform: [ linux ]
        arch: [ amd64, arm, arm64 ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Version number
        id: vars
        run: echo ::set-output name=branch::${GITHUB_REF##*/}
      - name: build
        env:
          TARGET: ${{ matrix.target }}
          PLATFORM: ${{ matrix.platform }}
          ARCH: ${{ matrix.arch }}
          RELEASE_VERSION: ${{ steps.vars.outputs.branch }}
        run: |
          GOOS=$PLATFORM GOARCH=$ARCH \
            go build \
              -ldflags "-X github.com/clambin/covid19/version.BuildVersion=$RELEASE_VERSION" \
              -o bld/$TARGET-$PLATFORM-$ARCH \
              cmd/$TARGET/$TARGET.go
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./bld/*
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          name: covid19-linux-arm
          path: ./bld
      - uses: actions/download-artifact@v2
        with:
          name: covid19-linux-arm64
          path: ./bld
      - uses: actions/download-artifact@v2
        with:
          name: covid19-linux-amd64
          path: ./bld
      - name: Fix permissions
        run: chmod +x bld/*
      - uses: docker/setup-qemu-action@v1.2.0
      - uses: docker/setup-buildx-action@v1.6.0
      - uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3.5.0
        id: docker_meta
        with:
          images: ghcr.io/clambin/covid19
          tags: |
            type=sha
            type=semver,pattern={{version}}
      - uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: ./build/Dockerfile
          platforms: linux/amd64,linux/arm,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
