name: Build

on:
  push:
    branches:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
       options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: checks
      run: |
        go get -u golang.org/x/lint/golint
        golint ./...
        go vet ./...
    # TODO: run postgres for DB tests
    - name: test
      run: |
        export pg_host=postgres
        export pg_port=5432
        export pg_db=postgres
        export pg_user=postgres
        export pg_password=postgres
        go test ./... -race -coverprofile=coverage.txt -covermode=atomic
    - uses: codecov/codecov-action@v1
      with:
        file: coverage.txt
        token: ${{ secrets.CODECOV_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: metadata for covid19mon
      id: covid19mon_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: clambin/covid19mon
        tag-sha: True
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile-covid19mon
        platforms: linux/amd64,linux/arm/v7
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.covid19mon_meta.outputs.tags }}
        labels: ${{ steps.covid19mon_meta.outputs.labels }}
    - name: metadata for covid19api
      id: covid19api_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: clambin/covid19api
        tag-sha: True
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}
    - uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/Dockerfile-covid19api
        platforms: linux/amd64,linux/arm/v7
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.covid19api_meta.outputs.tags }}
        labels: ${{ steps.covid19api_meta.outputs.labels }}
